### ISSUE TITLE
Bitten um Rückmeldung durch Korrektor da keine E-Mail im Profil hinterlegt ist.

### ISSUE THREAD

**Issue by MariusMay** [ProPra16/programmierpraktikum-abschlussprojekt-junger-des-binarius#2]
Wir hätten vor Abgabe noch ein paar Fragen und gerne eine generelle Rückmeldung zu unserem Programm. Danke im Voraus.

**Comment by n2o** [comment]
ping @gianperrone

**Comment by gianperrone** [comment]
Ich hinterleg eine, Gian.Perrone@uni-duesseldorf.de
